variables:
  NEXUS_URL: "artifacts.repo.mesal.ir"
  NEXUS_REPO: "docker-hosted"
  NAMESPACE: "wellness"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/i'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

stages:
  - build   
  - deploy  

include:
  # Production Build
  - project: 'devops/ci-templates'
    file: '/docker/build-and-push.yml'
    inputs:
      namespace: "${NAMESPACE}"
      image_name: "wn-front"
      nexus_url: "${NEXUS_URL}"
      nexus_repo: "${NEXUS_REPO}"
      image_tag: "latest"
      stage_name: "build"

  # Production Deploy
  - project: 'devops/ci-templates'
    file: '/deploy/ssh-deploy.yml'
    inputs:
      environment: "production"
      ssh_port: 2223
      deploy_command: "/home/production/server_deploy/repos/wellness/deploy-front.sh"
      image_to_deploy: "${NEXUS_URL}/${NEXUS_REPO}/${NAMESPACE}/wn-front:latest"
      stage_name: "deploy"
      needs_job: "build-for-production"

  # Development Build
  - project: 'devops/ci-templates'
    file: '/docker/build-and-push.yml'
    inputs:
      environment: "development"
      namespace: "${NAMESPACE}"
      image_name: "wn-dev-front"
      nexus_url: "${NEXUS_URL}"
      nexus_repo: "${NEXUS_REPO}"
      image_tag: "latest"
      stage_name: "build"
      build_args: '--build-arg MODE=development'
      trigger_type: "manual"

  # Development Deploy
  - project: 'devops/ci-templates'
    file: '/deploy/ssh-deploy.yml'
    inputs:
      environment: "development"
      ssh_port: 2223
      deploy_command: "/home/production/server_deploy/repos/wellness-dev/deploy-front.sh"
      image_to_deploy: "${NEXUS_URL}/${NEXUS_REPO}/${NAMESPACE}/wn-dev-front:latest"
      stage_name: "deploy"
      trigger_type: "auto"
      needs_job: "build-for-development"