workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/i'
      when: always
    
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    
    - when: never

stages:
  - build
  - deploy-prod    


include:
  - project: 'devops/ci-templates'
    file: '/docker/build-and-push.yml'
    inputs:
      namespace: "wellness"
      image_name: "wn-front"
      nexus_url: "artifacts.repo.mesal.ir"
      nexus_repo: "docker-hosted"
      image_tag: "latest"
      stage_name: "build"
      trigger_type: "manual"
       
  
  - project: 'devops/ci-templates'
    file: '/deploy/ssh-deploy.yml'
    inputs:
      environment: "production"
      ssh_port: 2223
      deploy_command: "/home/production/server_deploy/repos/wellness/deploy-front.sh"
      image_to_deploy: "artifacts.repo.mesal.ir/docker-hosted/wellness/wn-front:latest"
      stage_name: "deploy-prod"



